# All dimensionality reduction configurations

umap:
  - name: fast
    n_neighbors: 10
    min_dist: 0.1
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "random"
    subset_size: 150

  - name: detail
    n_neighbors: 20
    min_dist: 0.05
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

tsne:
  - name: fast
    perplexity: 25
    n_components: 2
    random_state: 42
    learning_rate: 200.0
    n_iter: 500
    early_exaggeration: 12.0
    n_iter_without_progress: 300
    min_grad_norm: 0.0000001
    metric: "euclidean"
    subset_strategy: "artist_first5"
    subset_size: 250

  - name: detail
    perplexity: 35
    n_components: 2
    random_state: 42
    learning_rate: 200.0
    n_iter: 1000
    early_exaggeration: 12.0
    n_iter_without_progress: 300
    min_grad_norm: 0.0000001
    metric: "euclidean"
    subset_strategy: "artist_first5"
    subset_size: 250

isomap:
  - name: basic
    n_neighbors: 5
    n_components: 2
    subset_strategy: "artist_first5"
    subset_size: 250

lle:
  - name: basic
    n_neighbors: 15
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

spectral:
  - name: basic
    n_neighbors: 10
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

mds:
  - name: basic
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250
