# configs.yaml
# All dimensionality reduction configurations

umap:
  - name: fast
    n_neighbors: 10
    min_dist: 0.1
    spread: 1.0
    set_op_mix_ratio: 1.0
    local_connectivity: 1.0
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "random"
    subset_size: 150

  - name: detail
    n_neighbors: 20
    min_dist: 0.05
    spread: 1.0
    set_op_mix_ratio: 1.0
    local_connectivity: 1.0
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

  - name: superdetail
    n_neighbors: 30
    min_dist: 0.01
    spread: 2.0
    set_op_mix_ratio: 0.5
    local_connectivity: 2.0
    n_components: 2
    metric: "manhattan"
    random_state: 123
    subset_strategy: "random"
    subset_size: 200

tsne:
  - name: fast
    perplexity: 25
    n_components: 2
    learning_rate: 200.0
    n_iter: 500
    early_exaggeration: 12.0
    n_iter_without_progress: 300
    min_grad_norm: 0.0000001
    metric: "euclidean"
    random_state: 42
    early_exaggeration_iter: 250
    theta: 0.5
    negative_gradient_method: "fft"
    initialization: "pca"
    n_jobs: 1
    subset_strategy: "artist_first5"
    subset_size: 250

  - name: detail
    perplexity: 35
    n_components: 2
    learning_rate: 200.0
    n_iter: 1000
    early_exaggeration: 12.0
    n_iter_without_progress: 300
    min_grad_norm: 0.0000001
    metric: "euclidean"
    random_state: 42
    early_exaggeration_iter: 250
    theta: 0.5
    negative_gradient_method: "fft"
    initialization: "pca"
    n_jobs: 1
    subset_strategy: "artist_first5"
    subset_size: 250

isomap:
  - name: basic
    n_neighbors: 5
    n_components: 2
    subset_strategy: "artist_first5"
    subset_size: 250

lle:
  - name: basic
    n_neighbors: 15
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

spectral:
  - name: basic
    n_neighbors: 10
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

mds:
  - name: basic
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

sammon_sammon_random:
  - name: test_random
    n: 2
    display: 0
    inputdist: raw
    maxhalves: 20
    maxiter: 500
    tolfun: 1e-9
    init: random
    subset_strategy: random
    subset_size: 40

sammon_random:
  - name: test_random
    n_dims: 2
    n_iter: 500
    tol: 1e-9
    input_type: vector
    random_state: 42
    subset_strategy: random
    subset_size: 40

pca:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

ipca:
  - name: fast
    n_components: 2
    batch_size: 200
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

svd:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

fa:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

ica:
  - name: fast
    n_components: 2
    max_iter: 500
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

agg:
  - name: fast
    n_clusters: 2
    subset_strategy: "artist_first5"
    subset_size: 250

kpca:
  - name: fast
    n_components: 2
    kernel: "rbf"
    gamma: 1.0
    fit_inverse_transform: true
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

nystroem_pca:
  - name: fast
    n_components: 2
    nystroem_components: 200
    kernel: "rbf"
    gamma: 1.0
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

grp:
  - name: fast
    n_components: 2
    eps: null
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

srp:
  - name: fast
    n_components: 2
    density: auto
    eps: null
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

nmf:
  - name: fast
    n_components: 2
    init: nndsvda
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

dictlearn:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250
