# configs.yaml
# All dimensionality reduction configurations

umap:
  - name: fast
    n_neighbors: 10
    min_dist: 0.1
    spread: 1.0
    set_op_mix_ratio: 1.0
    local_connectivity: 1.0
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "random"
    subset_size: 150
  - name: edge_low_neighbors
    n_neighbors: 2
    min_dist: 0.0
    spread: 0.5
    set_op_mix_ratio: 0.1
    local_connectivity: 1.0
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "random"
    subset_size: 40
  - name: edge_high_neighbors
    n_neighbors: 100
    min_dist: 0.99
    spread: 2.0
    set_op_mix_ratio: 1.0
    local_connectivity: 5.0
    n_components: 2
    metric: "cosine"
    random_state: 123
    subset_strategy: "artist_first5"
    subset_size: 400
  - name: rand_1
    n_neighbors: 20
    min_dist: 0.5
    spread: 1.0
    set_op_mix_ratio: 0.5
    local_connectivity: 2.0
    n_components: 2
    metric: "manhattan"
    random_state: 999
    subset_strategy: "random"
    subset_size: 150
  - name: rand_2
    n_neighbors: 10
    min_dist: 0.1
    spread: 1.0
    set_op_mix_ratio: 0.5
    local_connectivity: 1.0
    n_components: 2
    metric: "euclidean"
    random_state: 123
    subset_strategy: "artist_first5"
    subset_size: 250
  - name: rand_3
    n_neighbors: 50
    min_dist: 0.01
    spread: 2.0
    set_op_mix_ratio: 0.1
    local_connectivity: 5.0
    n_components: 2
    metric: "cosine"
    random_state: 42
    subset_strategy: "random"
    subset_size: 200

  - name: detail
    n_neighbors: 20
    min_dist: 0.05
    spread: 1.0
    set_op_mix_ratio: 1.0
    local_connectivity: 1.0
    n_components: 2
    metric: "euclidean"
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

  - name: superdetail
    n_neighbors: 30
    min_dist: 0.01
    spread: 2.0
    set_op_mix_ratio: 0.5
    local_connectivity: 2.0
    n_components: 2
    metric: "manhattan"
    random_state: 123
    subset_strategy: "random"
    subset_size: 200

tsne:
  - name: fast
    perplexity: 25
    n_components: 2
    learning_rate: 200.0
    n_iter: 500
    early_exaggeration: 12.0
    n_iter_without_progress: 300
    min_grad_norm: 0.0000001
    metric: "euclidean"
    random_state: 42
    early_exaggeration_iter: 250
    theta: 0.5
    negative_gradient_method: "fft"
    initialization: "pca"
    n_jobs: 1
    subset_strategy: "artist_first5"
    subset_size: 250
  - name: edge_low_perplexity
    perplexity: 5
    n_components: 2
    learning_rate: 10.0
    n_iter: 250
    early_exaggeration: 4.0
    n_iter_without_progress: 100
    min_grad_norm: 0.0000001
    metric: "euclidean"
    random_state: 42
    early_exaggeration_iter: 100
    theta: 0.1
    negative_gradient_method: "fft"
    initialization: "random"
    n_jobs: 1
    subset_strategy: "random"
    subset_size: 40
  - name: edge_high_perplexity
    perplexity: 100
    n_components: 2
    learning_rate: 1000.0
    n_iter: 1000
    early_exaggeration: 32.0
    n_iter_without_progress: 500
    min_grad_norm: 0.00001
    metric: "cosine"
    random_state: 123
    early_exaggeration_iter: 500
    theta: 0.8
    negative_gradient_method: "bh"
    initialization: "pca"
    n_jobs: 2
    subset_strategy: "artist_first5"
    subset_size: 400
  - name: rand_1
    perplexity: 30
    n_components: 2
    learning_rate: 200.0
    n_iter: 500
    early_exaggeration: 12.0
    n_iter_without_progress: 300
    min_grad_norm: 0.000001
    metric: "euclidean"
    random_state: 999
    early_exaggeration_iter: 250
    theta: 0.5
    negative_gradient_method: "fft"
    initialization: "pca"
    n_jobs: 1
    subset_strategy: "random"
    subset_size: 150
  - name: rand_2
    perplexity: 50
    n_components: 2
    learning_rate: 500.0
    n_iter: 750
    early_exaggeration: 16.0
    n_iter_without_progress: 400
    min_grad_norm: 0.00001
    metric: "cosine"
    random_state: 321
    early_exaggeration_iter: 300
    theta: 0.7
    negative_gradient_method: "fft"
    initialization: "random"
    n_jobs: 2
    subset_strategy: "artist_first5"
    subset_size: 250

isomap:
  - name: basic
    n_neighbors: 5
    n_components: 2
    subset_strategy: "artist_first5"
    subset_size: 250
  - name: edge_low_neighbors
    n_neighbors: 2
    n_components: 2
    subset_strategy: "random"
    subset_size: 40
  - name: edge_high_neighbors
    n_neighbors: 20
    n_components: 2
    subset_strategy: "artist_first5"
    subset_size: 400
  - name: rand_1
    n_neighbors: 10
    n_components: 2
    subset_strategy: "random"
    subset_size: 150
  - name: rand_2
    n_neighbors: 5
    n_components: 2
    subset_strategy: "artist_first5"
    subset_size: 250

lle:
  - name: basic
    n_neighbors: 15
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250
  - name: edge_low_neighbors
    n_neighbors: 2
    n_components: 2
    random_state: 42
    subset_strategy: "random"
    subset_size: 40
  - name: edge_high_neighbors
    n_neighbors: 30
    n_components: 2
    random_state: 123
    subset_strategy: "artist_first5"
    subset_size: 400
  - name: rand_1
    n_neighbors: 10
    n_components: 2
    random_state: 999
    subset_strategy: "random"
    subset_size: 150
  - name: rand_2
    n_neighbors: 15
    n_components: 2
    random_state: 321
    subset_strategy: "artist_first5"
    subset_size: 250

spectral:
  - name: basic
    n_neighbors: 10
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250
  - name: edge_low_neighbors
    n_neighbors: 2
    n_components: 2
    random_state: 42
    subset_strategy: "random"
    subset_size: 40
  - name: edge_high_neighbors
    n_neighbors: 30
    n_components: 2
    random_state: 123
    subset_strategy: "artist_first5"
    subset_size: 400
  - name: rand_1
    n_neighbors: 10
    n_components: 2
    random_state: 999
    subset_strategy: "random"
    subset_size: 150
  - name: rand_2
    n_neighbors: 15
    n_components: 2
    random_state: 321
    subset_strategy: "artist_first5"
    subset_size: 250

mds:
  - name: basic
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250
  - name: edge_low_components
    n_components: 2
    random_state: 42
    subset_strategy: "random"
    subset_size: 40
  - name: edge_high_components
    n_components: 2
    random_state: 123
    subset_strategy: "artist_first5"
    subset_size: 400
  - name: rand_1
    n_components: 2
    random_state: 999
    subset_strategy: "random"
    subset_size: 150
  - name: rand_2
    n_components: 2
    random_state: 321
    subset_strategy: "artist_first5"
    subset_size: 250

sammon_random:
  - name: test_random
    n_dims: 2
    n_iter: 500
    tol: 1e-9
    input_type: vector
    random_state: 42
    subset_strategy: random
    subset_size: 40

pca:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

ipca:
  - name: fast
    n_components: 2
    batch_size: 200
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

svd:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

fa:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

ica:
  - name: fast
    n_components: 2
    max_iter: 500
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

agg:
  - name: fast
    n_clusters: 2
    subset_strategy: "artist_first5"
    subset_size: 250

kpca:
  - name: fast
    n_components: 2
    kernel: "rbf"
    gamma: 1.0
    fit_inverse_transform: true
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

nystroem_pca:
  - name: fast
    n_components: 2
    nystroem_components: 200
    kernel: "rbf"
    gamma: 1.0
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

grp:
  - name: fast
    n_components: 2
    eps: null
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

srp:
  - name: fast
    n_components: 2
    density: auto
    eps: null
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

nmf:
  - name: fast
    n_components: 2
    init: nndsvda
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

dictlearn:
  - name: fast
    n_components: 2
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250

phate:
  - name: fast
    n_components: 2
    knn: 5
    decay: 40
    t: auto
    gamma: 1
    random_state: 42
    subset_strategy: "artist_first5"
    subset_size: 250
  # Practical config: higher knn, lower decay
  - name: practical_2
    n_components: 2
    knn: 15
    decay: 20
    t: auto
    gamma: 1
    random_state: 123
    subset_strategy: "random"
    subset_size: 200
  # Edge-case: very high knn, low gamma
  - name: edge_high_knn
    n_components: 2
    knn: 50
    decay: 40
    t: auto
    gamma: 0.1
    random_state: 321
    subset_strategy: "artist_first5"
    subset_size: 250
  # Edge-case: low decay, high gamma
  - name: edge_low_decay
    n_components: 2
    knn: 5
    decay: 2
    t: auto
    gamma: 1
    random_state: 999
    subset_strategy: "random"
    subset_size: 100

trimap:
  - name: fast
    n_dims: 2
    n_inliers: 12
    n_outliers: 4
    n_random: 3
    distance: "euclidean"
    weight_temp: 0.5
    lr: 0.1
    n_iters: 400
    random_state: 42
    opt_method: "dbd"
    apply_pca: true
    subset_strategy: "random"
    subset_size: 150
  - name: detail
    n_dims: 2
    n_inliers: 20
    n_outliers: 10
    n_random: 10
    distance: "euclidean"
    weight_temp: 0.5
    lr: 0.05
    n_iters: 1000
    random_state: 42
    opt_method: "dbd"
    apply_pca: true
    subset_strategy: "artist_first5"
    subset_size: 250
  # SAFE: Only n_inliers changed from fast
  - name: safe_inliers_16
    n_dims: 2
    n_inliers: 16
    n_outliers: 4
    n_random: 3
    distance: "euclidean"
    weight_temp: 0.5
    lr: 0.1
    n_iters: 400
    random_state: 43
    opt_method: "dbd"
    apply_pca: true
    subset_strategy: "random"
    subset_size: 150
  # SAFE: Only lr changed from fast
  - name: safe_lr_0.05
    n_dims: 2
    n_inliers: 12
    n_outliers: 4
    n_random: 3
    distance: "euclidean"
    weight_temp: 0.5
    lr: 0.05
    n_iters: 400
    random_state: 44
    opt_method: "dbd"
    apply_pca: true
    subset_strategy: "random"
    subset_size: 150
  # The following configs are commented out due to segfaults:
  # - name: practical_3
  #   n_dims: 2
  #   n_inliers: 30
  #   n_outliers: 15
  #   n_random: 10
  #   distance: "cosine"
  #   weight_temp: 0.7
  #   lr: 0.08
  #   n_iters: 600
  #   random_state: 321
  #   opt_method: "dbd"
  #   apply_pca: true
  #   subset_strategy: "random"
  #   subset_size: 200
  # - name: edge_high_inliers
  #   n_dims: 2
  #   n_inliers: 50
  #   n_outliers: 1
  #   n_random: 5
  #   distance: "euclidean"
  #   weight_temp: 0.3
  #   lr: 0.05
  #   n_iters: 800
  #   random_state: 888
  #   opt_method: "dbd"
  #   apply_pca: false
  #   subset_strategy: "artist_first5"
  #   subset_size: 250
  # - name: edge_high_lr
  #   n_dims: 2
  #   n_inliers: 10
  #   n_outliers: 5
  #   n_random: 3
  #   distance: "manhattan"
  #   weight_temp: 1.0
  #   lr: 0.5
  #   n_iters: 100
  #   random_state: 555
  #   opt_method: "sgd"
  #   apply_pca: true
  #   subset_strategy: "random"
  #   subset_size: 100

spacemap:
  - name: fast
    n_components: 2
    n_near_field: 21
    n_middle_field: 50
    d_local: 0
    d_global: 4.5
    eta: 0.6
    n_epochs: 200
    init: spectral
    metric: euclidean
    verbose: true
    plot_results: false
    num_plots: 50
    subset_strategy: artist_first5
    subset_size: 250
  # Practical config: more epochs, different eta
  - name: practical_2
    n_components: 2
    n_near_field: 25
    n_middle_field: 60
    d_local: 1
    d_global: 4.0
    eta: 0.8
    n_epochs: 400
    init: spectral
    metric: euclidean
    verbose: false
    plot_results: false
    num_plots: 50
    subset_strategy: random
    subset_size: 200
  # Edge-case: very high n_near_field, low d_local
  - name: edge_high_near
    n_components: 2
    n_near_field: 100
    n_middle_field: 30
    d_local: 0
    d_global: 2.0
    eta: 0.5
    n_epochs: 150
    init: random
    metric: cosine
    verbose: true
    plot_results: true
    num_plots: 10
    subset_strategy: artist_first5
    subset_size: 250
  # Edge-case: very low eta, high d_global
  - name: edge_low_eta
    n_components: 2
    n_near_field: 10
    n_middle_field: 80
    d_local: 2
    d_global: 10.0
    eta: 0.01
    n_epochs: 300
    init: spectral
    metric: euclidean
    verbose: false
    plot_results: false
    num_plots: 20
    subset_strategy: random
    subset_size: 100

glle:
  - name: glle_em_fast
    method: GLLE
    k_neighbors: 10
    max_iterations: 50
    n_components: 2
    n_generation_of_embedding: 3
    subset_strategy: random
    subset_size: 150
    verbosity: 1

  - name: glle_direct_long
    method: GLLE_DirectSampling
    k_neighbors: 15
    max_iterations: 100
    n_components: 2
    n_generation_of_embedding: 5
    subset_strategy: random
    subset_size: 150
    verbosity: 1
