- method: agg
  config_id: 1
- method: dictlearn
  config_id: 1
- method: fa
  config_id: 1
- method: grp
  config_id: 1
- method: grp
  config_id: 2
- method: grp
  config_id: 3
- method: ica
  config_id: 1
- method: ipca
  config_id: 1
- method: isomap
  config_id: 1
- method: isomap
  config_id: 2
- method: isomap
  config_id: 4
- method: kpca
  config_id: 1
- method: lle
  config_id: 1
- method: lle
  config_id: 2
- method: lle
  config_id: 4
- method: mds
  config_id: 1
- method: mds
  config_id: 2
- method: mds
  config_id: 4
- method: nmf
  config_id: 1
- method: nystroem_pca
  config_id: 1
- method: pca
  config_id: 1
- method: phate
  config_id: 1
- method: phate
  config_id: 2
- method: phate
  config_id: 3
- method: phate
  config_id: 4
- method: sammon_random
  config_id: 1
- method: spacemap
  config_id: 1
- method: spacemap
  config_id: 2
- method: spacemap
  config_id: 3
- method: spacemap
  config_id: 4
- method: spectral
  config_id: 1
- method: spectral
  config_id: 2
- method: spectral
  config_id: 4
- method: spectral
  config_id: 5
- method: srp
  config_id: 1
- method: srp
  config_id: 2
- method: srp
  config_id: 3
- method: svd
  config_id: 1
- method: trimap
  config_id: 1
- method: trimap
  config_id: 2
- method: trimap
  config_id: 4
- method: trimap
  config_id: 5
- method: tsne
  config_id: 1
- method: tsne
  config_id: 2
- method: tsne
  config_id: 4
- method: tsne
  config_id: 5
- method: umap
  config_id: 1
- method: umap
  config_id: 2
- method: umap
  config_id: 3
- method: umap
  config_id: 5
- method: umap
  config_id: 6
- method: umap
  config_id: 8
